ServiceName = "svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820"
Name = ""
Description = "E2E integration test"
Owners = ["eyal.dulb@gmail.com"]
ServerFramework = "go-server"
ServerMain = ""
ArtifactRepository = "ghcr.io/koalaops/fake-registry"
Port = 8080
ContainerEnvFileName = ".env"
EnvironmentConfigFileName = "environment-values.env"
LegacyIngressPatchEnabled = false
EnvNamePrefixEnabled = false
LegacyObjectSuffixEnabled = false

[KoalaVersionInfo]
  Version = ""
  DeployWorkflowVersion = ""

[Repo]
  Name = "svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820"
  GitUser = "koala-sandbox"
  URL = ""
  Path = ""
  IsMonorepo = false
  Token = ""

[TemplateConfig]
  Repo = ""
  Path = ""

[OpenAPIConfig]
  SpecPath = ""
  QueryPath = ""
  CodegenTool = ""

[[Environments]]
  Name = "dev"
  Namespace = "dev"
  Cluster = "nonprod-cluster-us-east1"
  Location = ""
  CloudProvider = ""
  IngressEnabled = false
  IngressHost = ""

[SSLConfig]
  CertName = ""
  Issuer = ""
  IssuerContactEmail = ""

[Metrics]
  Collector = ""
  [Metrics.Endpoint]
    Path = ""
    Port = 0
    Scheme = ""
    Interval = ""

[Tracing]
  Backend = ""
  URL = ""

[Profiling]
  Tool = ""
