apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820
build:
  tagPolicy:
    sha256: {}
  platforms: ["linux/amd64", "darwin/arm64"]
  artifacts:
  - image: ghcr.io/koalaops/fake-registry/svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - "go.mod"
          - "**/*.go"
manifests:
  kustomize:
    paths:
    - deploy/overlays/dev
profiles:
- name: prod
  manifests:
    kustomize:
      paths:
      - deploy/overlays/prod
