apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820
  labels:
    app: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-image-pull-secret
      containers:
      - name: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820
        image: ghcr.io/koalaops/fake-registry/svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820:latest
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820-container-vars
    metadata:
      labels:
        app: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820
