apiVersion: kustomize.config.k8s.io/v1beta1
labels:
- pairs:
    app: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820
configMapGenerator:
- name: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820-environment-values
  envs:
  - environment-values.env
- name: svc-new-single-inrepo-port-ingress-noautodeploy-20250724131820-container-vars
  envs:
  - .env
generatorOptions:
  disableNameSuffixHash: true # use a static name
kind: Kustomization
resources:
- deployment.yaml
- service.yaml